- name: Delete old workflow runs
  # You may pin to the exact commit or the version.
  # uses: MajorScruffy/delete-old-workflow-runs@78b5af714fefaefdf74862181c467b061782719e
  uses: MajorScruffy/delete-old-workflow-runs@v0.3.0
  with:
    # The repository for which to delete workflow runs.
    repository: 
    # The path to the workflow's .yml file.
    workflow: # optional
    # Consider only the workflows older than the given number of seconds.
    older-than-seconds: # optional
    # Consider only the workflows created before this date for deletion.
    created-before: # optional
    # Returns someone's workflow runs. Use the login for the user who created the push associated with the check suite or workflow run.
    actor: # optional
    # Returns workflow runs associated with a branch. Use the name of the branch of the push.
    branch: # optional
    # Returns workflow run triggered by the event you specify. For example, push, pull_request or issue.
    event: # optional
    # Returns workflow runs with the given status. Can be one of queued, in_progress, or completed.
    status: # optional
    # Set to true to preview the changes made by this action without deleting any workflow runs.
    what-if: # optional
