name: Publish to PowerShell Gallery
on: [workflow_dispatch]
defaults:
  run:
    shell: pwsh
jobs:
  publish-to-gallery:
    name: Build and Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Publish
        env:
          NUGETAPIKEY: ${{ secrets.NUGETAPIKEY }}
        run: function getvar ($name) { return [Environment]::GetEnvironmentVariable($env:RUN_ID + $name) }; $BuildScript = [IO.Path]::Combine((Get-Location).Path, 'build.ps1'); & $BuildScript -Task Test; Publish-Module -Path ([IO.path]::Combine((getvar 'BuildOutput') , (getvar 'ProjectName') , (getvar 'BuildNumber'))) -NuGetApiKey $Env:NUGETAPIKEY -Repository PSGallery -Verbose
