name: Publish to PowerShell Gallery
on: [workflow_dispatch]
defaults:
  run:
    shell: pwsh
jobs:
  publish-to-gallery:
    name: Build and Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Publish
        env:
          NUGETAPIKEY: ${{ secrets.NUGETAPIKEY }}
        run: $BuildScript = [IO.Path]::Combine((Get-Location).Path, 'build.ps1'); & $BuildScript; Publish-Module -Path ([IO.path]::Combine([Environment]::GetEnvironmentVariable($env:RUN_ID + 'BuildOutput') , [Environment]::GetEnvironmentVariable($env:RUN_ID + 'ProjectName') , [Environment]::GetEnvironmentVariable($env:RUN_ID + 'BuildNumber'))) -NuGetApiKey $Env:NUGETAPIKEY -Repository PSGallery -Verbose
